### ISSUE TITLE
Приложение падает при "bucEnabled": true

### ISSUE THREAD

**Issue by ptah-alexs** [bookpauk/liberama#45]
Версия liberama 1.1.3 из releases гитхаба

```
$ ./liberama
2023-10-16 16:59:38.676  INFO: liberama v1.1.3, Node.js v16.16.0
2023-10-16 16:59:38.676  INFO: Initializing
2023-10-16 16:59:38.691  INFO: Open "app" begin
2023-10-16 16:59:38.764  INFO: Open "app" end
2023-10-16 16:59:38.772  INFO: Open "reader-storage" begin
2023-10-16 16:59:38.849  INFO: Open "reader-storage" end
2023-10-16 16:59:38.959  INFO: Server "1" is ready on http://0.0.0.0:44080, mode: reader
2023-10-16 16:59:38.959  INFO: client: clean 'buc' table begin
2023-10-16 16:59:38.959  INFO: BUC Client Worker started
2023-10-16 16:59:38.962  WARN: clean dir /home/user/MyDownloads/software/liberama/.liberama/public-files/tmp, maxSize=536870912, found 1 files, total size=315372
2023-10-16 16:59:38.962  WARN: removed 0 files
2023-10-16 16:59:38.962  INFO: client: clean 'buc' table end
2023-10-16 16:59:38.962  INFO: client: sync 'buc' table begin
2023-10-16 16:59:38.962 FATAL ERROR: Signal "uncaughtException" received, error: "SyntaxError: Invalid URL: undefined
    at initAsClient (/snapshot/liberama/node_modules/ws/lib/websocket.js:673:13)
    at new WebSocket (/snapshot/liberama/node_modules/ws/lib/websocket.js:85:7)
    at /snapshot/liberama/server/core/WebSocketConnection.js:97:31
    at /snapshot/liberama/server/core/WebSocketConnection.js:143:11
    at new Promise (<anonymous>)
    at WebSocketConnection._open (/snapshot/liberama/server/core/WebSocketConnection.js:74:16)
    at WebSocketConnection.send (/snapshot/liberama/server/core/WebSocketConnection.js:166:20)
    at BUCClient.wsGetBuc (/snapshot/liberama/server/core/BookUpdateChecker/BUCClient.js:59:42)
    at BUCClient.periodicSync (/snapshot/liberama/server/core/BookUpdateChecker/BUCClient.js:221:28)", exiting...
2023-10-16 16:59:38.963  WARN: clean dir /home/user/MyDownloads/software/liberama/.liberama/public-files/upload, maxSize=209715200, found 2 files, total size=343756
2023-10-16 16:59:38.963  WARN: removed 0 files

```

**Comment by bookpauk** [comment]
bucEnabled работает только в связке с параметром bucServer вида:
    "bucServer": {
        "url": "wss://<ip-address>:<port>",
        "accessToken": "qwertyuiopASDFGHJKL"
    }

Т.е. чтобы правильно настроить работу с сервером обновлений, надо сначала его развернуть как отдельное приложение (режим "book_update_checker"). Там могут быть нюансы, поэтому описание в README такое куцее.
Если сильно хочется развернуть свой собственный сервер обновлений, пишите на почту.
